travis:
  secure:
    BINSTAR_TOKEN: dH+gPidhBLp+NAE4OPp2/bG/cqzhSTzAbBm0eR/7uhM1jE4IAFUA+q0DkHK7JIFF4j+nVomsvsYNq8st+XnSKp1mnASmzG0+UMTAFwyWjyEpR0nGmuU2jTEkDp4lmhqorMR8BYCXih0F51k61n+aP4nkIEAy9LzjNwcw5t+cFF3Px9IG/sxgwXRhcaWWS8Fb5tt1jHDG/IGCwM5ZpIcNxc2I75UZISpOAVGndrqv+E+E6sE2zAdz8xAmCp5oqfqO/J4pwq3jtX4y+WGUhrF5viWr54Jy2ez9OTkgl1xsYdIdBPAkKVJbGgoAYnp6q6x5vdPhk3Sb2OKbphSDDJpjrvzrcb0gd9azAKG4sNDTyXjq1H/gHryYf0s2gThltzHrdmiqF/CqKjiF+RZd+QVf8l1GMITSgiBHZ8tcBcI/uUDes9SR75EdCh9QyZ0iyjFaLtAEKrY/Y3RAXJfG2Z+uwgteVclkEyu/XS1jHDArF+wpqvQuUj7KfCqPeiNEHzrANex6/pJqzpSJbZaKum3N4v5QcDXyZXOXyMsk4PU61k9BkjFdTx5Y8Ci/JEvf7Sk+q96upEvc+mIemXCCJWe0ZhsRJsKSaVDUyNcTJX4y4BiEhGciGP/ZYO1jQCgTnBkGKgmQEaeBGCVr/ugCt0P8bLKoNQyu1VKJTzq8tos02Y8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
