{% set version = "r7271.1a4dbf6" %}

package:
  name: kaldi
  version: {{ version }}

source:
  git_url: https://github.com/kaldi-asr/kaldi.git
  git_rev: cc745dd7723bd99d0340e3b23a8215977bee3168

build:
  number: 2
  skip: true  # [not linux]
    
requirements:
  build:
    - gcc >=4.8.5
    - openfst
    - openblas 0.2.20|0.2.20.*
    - speex
  run:
    - libgcc >=4.8.5
    - openfst
    - openblas 0.2.20|0.2.20.*
    - speex
    
about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: http://kaldi-asr.org/forums.html

extra:
  recipe-maintainers:
    - mcernak
