name: lid
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates
  - certifi
  - intel-openmp
  - libffi
  - libogg
  - mkl
  - mkl_fft
  - mkl_random
  - numpy
  - numpy-base
  - openblas
  - openssl
  - pip=18.1
  - python=3
  - scikit-learn
  - scipy
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
